ContactFrom + UserInfo
smartblog/leanpub-app pull request #4
Opened 2020-08-26 10:13 UTC by smartblog

2020-08-26 10:24 UTC, index01d requested changes

2020-08-26 10:24 UTC, index01d commented on src/BookTable.js
> +        <div>Pages: {pages}</div>
можно выделить также компонент
`<Row label='Pages'>{pages}</Row>`, чтобы в случае необходимости быстро задать необходимые атрибуты для всех строк информации о книге исправив только один компонент (избежать дублирования этих атрибутов).

2020-08-26 10:24 UTC, index01d commented on src/ContactForm.js
> +        />
чтобы не дублировать настройку элементов можно завести высокоуровневый компонент поля ввода для формы
```js
  <Field 
    label='Question'
    type='textarea' 
    placeholder='Your question' 
    name='question' 
    value={question}
    onChange={onChange} 
/>
```

2020-08-26 10:24 UTC, index01d commented on src/index.js
> +import authContext from './authContext';
лучше именовать с большой буквы `AuthContext`, тк компоненты принято именовать так

2020-08-27 19:08 UTC, index01d approved these changes

2020-08-27 19:08 UTC, index01d commented on src/ContactForm.js
> +        <FieldInput label='Name' placeholder='Enter your Name' value={this.state.name} onChange={(e) => this.setField('name', e)}/>
здесь можно просто передать `onChange={onChange}`

```
onChange(e) {
  this.setField(e.target.name, e.target.value)
}
```

2020-08-27 19:08 UTC, index01d commented on src/ContactForm.js
> +const FieldTextarea = ({label, placeholder, value, onChange}) => (
мало чем отличается от FieldInput,
можно было просто сделать трюк
```
const Element = type === 'textarea' ? 'textarea' : 'input'
...
<Element onChange={onChange} placeholder={placeholder} value={value} />
```

2020-08-29 06:27 UTC, smartblog commented on src/ContactForm.js
> +const FieldTextarea = ({label, placeholder, value, onChange}) => (
Круто. Буду иметь ввиду. Для меня такие трюки пока магия =)) Но постараюсь разобраться

2020-08-29 06:28 UTC, smartblog commented on src/ContactForm.js
> +        <FieldInput label='Name' placeholder='Enter your Name' value={this.state.name} onChange={(e) => this.setField('name', e)}/>
Принял. Применю

2020-09-02 09:54 UTC, merged